apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-simple-app
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.5
  mainClass: UserTest
  mainApplicationFile: "http://minio-1742981469.default.svc:9000/bucket/Simple_Project-assembly-1.0.jar"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark
    envVars:
      MINIO_ENDPOINT: "http://minio-1742981469.default.svc:9000"
      MINIO_ACCESS_KEY: "rootuser"
      MINIO_SECRET_KEY: "rootpass123"
      MINIO_BUCKET: "bucket"
      MINIO_FILE: "users.csv"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
